export const UPDATE_ESSENTIAL_DETAILS_ACTION =
  "UPDATE_ESSENTIAL_DETAILS_ACTION";
export const UPDATE_ESSENTIAL_DETAILS_LOADING =
  "UPDATE_ESSENTIAL_DETAILS_LOADING";
export const UPDATE_ESSENTIAL_DETAILS_SUCCESS =
  "UPDATE_ESSENTIAL_DETAILS_SUCCESS";
export const UPDATE_ESSENTIAL_DETAILS_ERROR = "UPDATE_ESSENTIAL_DETAILS_ERROR";
