export const UPDATE_ESSENTIAL_DETAILS_ACTION =
  "UPDATE_ESSENTIAL_DETAILS_ACTION";
export const UPDATE_ESSENTIAL_DETAILS_LOADING =
  "UPDATE_ESSENTIAL_DETAILS_LOADING";
export const UPDATE_ESSENTIAL_DETAILS_SUCCESS =
  "UPDATE_ESSENTIAL_DETAILS_SUCCESS";
export const UPDATE_ESSENTIAL_DETAILS_ERROR = "UPDATE_ESSENTIAL_DETAILS_ERROR";

export const PRESERVE_ESSENTIAL_DATA_ACTION = "PRESERVE_ESSENTIAL_DATA_ACTION";
export const PRESERVE_ESSENTIAL_DATA_SUCCESS =
  "PRESERVE_ESSENTIAL_DATA_SUCCESS";

export const CORE_BUSINESS_OPTIONS_ACTION = "CORE_BUSINESS_OPTIONS_ACTION";
export const CORE_BUSINESS_OPTIONS_LOADING = "CORE_BUSINESS_OPTIONS_LOADING";
export const CORE_BUSINESS_OPTIONS_SUCCESS = "CORE_BUSINESS_OPTIONS_SUCCESS";
export const CORE_BUSINESS_OPTIONS_ERROR = "CORE_BUSINESS_OPTIONS_ERROR";

export const MARKET_STAGE_OPTIONS_ACTION = "MARKET_STAGE_OPTIONS_ACTION";
export const MARKET_STAGE_OPTIONS_LOADING = "MARKET_STAGE_OPTIONS_LOADING";
export const MARKET_STAGE_OPTIONS_SUCCESS = "MARKET_STAGE_OPTIONS_SUCCESS";
export const MARKET_STAGE_OPTIONS_ERROR = "MARKET_STAGE_OPTIONS_ERROR";

export const EXPERTISE_OPTIONS_ACTION = "EXPERTISE_OPTIONS_ACTION";
export const EXPERTISE_OPTIONS_LOADING = "EXPERTISE_OPTIONS_LOADING";
export const EXPERTISE_OPTIONS_SUCCESS = "EXPERTISE_OPTIONS_SUCCESS";
export const EXPERTISE_OPTIONS_ERROR = "EXPERTISE_OPTIONS_ERROR";

export const FUNDING_OPTIONS_ACTION = "FUNDING_OPTIONS_ACTION";
export const FUNDING_OPTIONS_LOADING = "FUNDING_OPTIONS_LOADING";
export const FUNDING_OPTIONS_SUCCESS = "FUNDING_OPTIONS_SUCCESS";
export const FUNDING_OPTIONS_ERROR = "FUNDING_OPTIONS_ERROR";
