export const SIGNUP_ACTION = "SIGNUP_ACTION";
export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const GOOGLE_SIGNUP_ACTION = "GOOGLE_SIGNUP_ACTION";
export const GOOGLE_SIGNUP_LOADING = "GOOGLE_SIGNUP_LOADING";
export const GOOGLE_SIGNUP_SUCCESS = "GOOGLE_SIGNUP_SUCCESS";
export const GOOGLE_SIGNUP_ERROR = "GOOGLE_SIGNUP_ERROR";
