export const UPDATE_DETAILS_ACTION = "UPDATE_DETAILS_ACTION";
export const UPDATE_DETAILS_LOADING = "UPDATE_DETAILS_LOADING";
export const UPDATE_DETAILS_SUCCESS = "UPDATE_DETAILS_SUCCESS";
export const UPDATE_DETAILS_ERROR = "UPDATE_DETAILS_ERROR";

export const UPLOAD_LOGO_ACTION = "UPLOAD_LOGO_ACTION";
export const UPLOAD_LOGO_LOADING = "UPLOAD_LOGO_LOADING";
export const UPLOAD_LOGO_SUCCESS = "UPLOAD_LOGO_SUCCESS";
export const UPLOAD_LOGO_ERROR = "UPLOAD_LOGO_ERROR";
