export const Constants = {
  BASE_URL: "http://localhost:3001/api",
  ROLES: {
    STARTUP_INDIVIDUAL: "Startup or Individual",
    ORGANIZATION: "Organization",
    MENTOR_JUDGE: "Mentor / Judge",
  },
  Errors: {
    email: "Email is required",
    password: "Password is required",
    confirmPassword: "Confirm password is required",
    passwordMismatch: "Password does not match",
    role: "Role is required",
    verificationCode: "Verification code is required",
    name: "Name is required",
    logo: "Logo is required",
    website: "Website is required",
    invalid_website: "Invalid Website",
    location: "Location is required",
    incorporationDate: "Incorporation date is required",
    mobile: "Mobile is required",
    birthDate: "Birth date is required",
    industry: "Industry is required",
    service: "Service is required",
    technology: "Technology is required",
    businessModel: "Business model is required",
    targetMarket: "Target market is required",
    georgraphicalMarket: "Georgraphical market is required",
    companyDesciption: "Company desciption is required",
    coreBusiness: "Core business is required",
    marketStage: "Market stage is required",
    funding: "Funding is required",
    summary: "Summary is required",
    expertise: "Expertise is required",
  },
};
