export const SIGNIN_ACTION = "SIGNIN_ACTION";
export const SIGNIN_LOADING = "SIGNIN_LOADING";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";

export const LOGGEDIN_USER_ACTION = "LOGGEDIN_USER_ACTION";
export const LOGGEDIN_USER_LOADING = "LOGGEDIN_USER_LOADING";
export const LOGGEDIN_USER_SUCCESS = "LOGGEDIN_USER_SUCCESS";
export const LOGGEDIN_USER_ERROR = "LOGGEDIN_USER_ERROR";

export const GET_USER_ACTION = "GET_USER_ACTION";
export const GET_USER_LOADING = "GET_USER_LOADING";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const GOOGLE_LOGIN_ACTION = "GOOGLE_LOGIN_ACTION";
export const GOOGLE_LOGIN_LOADING = "GOOGLE_LOGIN_LOADING";
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_ERROR = "GOOGLE_LOGIN_ERROR";

export const LINKEDIN_LOGIN_ACTION = "LINKEDIN_LOGIN_ACTION";
export const LINKEDIN_LOGIN_LOADING = "LINKEDIN_LOGIN_LOADING";
export const LINKEDIN_LOGIN_SUCCESS = "LINKEDIN_LOGIN_SUCCESS";
export const LINKEDIN_LOGIN_ERROR = "LINKEDIN_LOGIN_ERROR";
