export const SIGNIN_ACTION = "SIGNIN_ACTION";
export const SIGNIN_LOADING = "SIGNIN_LOADING";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";

export const LOGGEDIN_USER_ACTION = "LOGGEDIN_USER_ACTION";
export const LOGGEDIN_USER_LOADING = "LOGGEDIN_USER_LOADING";
export const LOGGEDIN_USER_SUCCESS = "LOGGEDIN_USER_SUCCESS";
export const LOGGEDIN_USER_ERROR = "LOGGEDIN_USER_ERROR";
