export const ATTACH_JUDGING_CRITERIA_ACTION = "ATTACH_JUDGING_CRITERIA_ACTION";
export const ATTACH_JUDGING_CRITERIA_LOADING =
  "ATTACH_JUDGING_CRITERIA_LOADING";
export const ATTACH_JUDGING_CRITERIA_SUCCESS =
  "ATTACH_JUDGING_CRITERIA_SUCCESS";
export const ATTACH_JUDGING_CRITERIA_ERROR = "ATTACH_JUDGING_CRITERIA_ERROR";

export const GET_RATING_TYPES_ACTION = "GET_RATING_TYPES_ACTION";
export const GET_RATING_TYPES_LOADING = "GET_RATING_TYPES_LOADING";
export const GET_RATING_TYPES_SUCCESS = "GET_RATING_TYPES_SUCCESS";
export const GET_RATING_TYPES_ERROR = "GET_RATING_TYPES_ERROR";
