export const GET_ATTACHED_USERS_ACTION = "GET_ATTACHED_USERS_ACTION";
export const GET_ATTACHED_USERS_LOADING = "GET_ATTACHED_USERS_LOADING";
export const GET_ATTACHED_USERS_SUCCESS = "GET_ATTACHED_USERS_SUCCESS";
export const GET_ATTACHED_USERS_ERROR = "GET_ATTACHED_USERS_ERROR";
