export const ATTACH_SUMMARY_ACTION = "ATTACH_SUMMARY_ACTION";
export const ATTACH_SUMMARY_LOADING = "ATTACH_SUMMARY_LOADING";
export const ATTACH_SUMMARY_SUCCESS = "ATTACH_SUMMARY_SUCCESS";
export const ATTACH_SUMMARY_ERROR = "ATTACH_SUMMARY_ERROR";
