export const ATTACH_UPDATES_ACTION = "ATTACH_UPDATES_ACTION";
export const ATTACH_UPDATES_LOADING = "ATTACH_UPDATES_LOADING";
export const ATTACH_UPDATES_SUCCESS = "ATTACH_UPDATES_SUCCESS";
export const ATTACH_UPDATES_ERROR = "ATTACH_UPDATES_ERROR";

export const UPDATE_VIEW_ACTION = "UPDATE_VIEW_ACTION";
export const UPDATE_VIEW_LOADING = "UPDATE_VIEW_LOADING";
export const UPDATE_VIEW_SUCCESS = "UPDATE_VIEW_SUCCESS";
export const UPDATE_VIEW_ERROR = "UPDATE_VIEW_ERROR";
