export const ATTACH_UPDATES_ACTION = "ATTACH_UPDATES_ACTION";
export const ATTACH_UPDATES_LOADING = "ATTACH_UPDATES_LOADING";
export const ATTACH_UPDATES_SUCCESS = "ATTACH_UPDATES_SUCCESS";
export const ATTACH_UPDATES_ERROR = "ATTACH_UPDATES_ERROR";
