export const ATTACH_GUIDELINE_ACTION = "ATTACH_GUIDELINE_ACTION";
export const ATTACH_GUIDELINE_LOADING = "ATTACH_GUIDELINE_LOADING";
export const ATTACH_GUIDELINE_SUCCESS = "ATTACH_GUIDELINE_SUCCESS";
export const ATTACH_GUIDELINE_ERROR = "ATTACH_GUIDELINE_ERROR";
