export const ATTACH_TIMELINE_ACTION = "ATTACH_TIMELINE_ACTION";
export const ATTACH_TIMELINE_LOADING = "ATTACH_TIMELINE_LOADING";
export const ATTACH_TIMELINE_SUCCESS = "ATTACH_TIMELINE_SUCCESS";
export const ATTACH_TIMELINE_ERROR = "ATTACH_TIMELINE_ERROR";
