export const ATTACH_TIMELINE_ACTION = "ATTACH_TIMELINE_ACTION";
export const ATTACH_TIMELINE_LOADING = "ATTACH_TIMELINE_LOADING";
export const ATTACH_TIMELINE_SUCCESS = "ATTACH_TIMELINE_SUCCESS";
export const ATTACH_TIMELINE_ERROR = "ATTACH_TIMELINE_ERROR";

export const TIMELINE_STATES_ACTION = "TIMELINE_STATES_ACTION";
export const TIMELINE_STATES_LOADING = "TIMELINE_STATES_LOADING";
export const TIMELINE_STATES_SUCCESS = "TIMELINE_STATES_SUCCESS";
export const TIMELINE_STATES_ERROR = "TIMELINE_STATES_ERROR";
