export const ATTACH_JUDGING_ACTIVITY_ACTION = "ATTACH_JUDGING_ACTIVITY_ACTION";
export const ATTACH_JUDGING_ACTIVITY_LOADING =
  "ATTACH_JUDGING_ACTIVITY_LOADING";
export const ATTACH_JUDGING_ACTIVITY_SUCCESS =
  "ATTACH_JUDGING_ACTIVITY_SUCCESS";
export const ATTACH_JUDGING_ACTIVITY_ERROR = "ATTACH_JUDGING_ACTIVITY_ERROR";
