export const SEARCH_ALL_ACTION = "SEARCH_ALL_ACTION";
export const SEARCH_ALL_LOADING = "SEARCH_ALL_LOADING";
export const SEARCH_ALL_SUCCESS = "SEARCH_ALL_SUCCESS";
export const SEARCH_ALL_ERROR = "SEARCH_ALL_ERROR";
