export const LINKEDIN_DATA_ACTION = "LINKEDIN_DATA_ACTION";
export const LINKEDIN_DATA_LOADING = "LINKEDIN_DATA_LOADING";
export const LINKEDIN_DATA_SUCCESS = "LINKEDIN_DATA_SUCCESS";
export const LINKEDIN_DATA_ERROR = "LINKEDIN_DATA_ERROR";
