export const INVITE_PARTICIPANTS_ACTION = "INVITE_PARTICIPANTS_ACTION";
export const INVITE_PARTICIPANTS_LOADING = "INVITE_PARTICIPANTS_LOADING";
export const INVITE_PARTICIPANTS_SUCCESS = "INVITE_PARTICIPANTS_SUCCESS";
export const INVITE_PARTICIPANTS_ERROR = "INVITE_PARTICIPANTS_ERROR";
