export const UPDATE_STATUS_ACTION = "UPDATE_STATUS_ACTION";
export const UPDATE_STATUS_LOADING = "UPDATE_STATUS_LOADING";
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS";
export const UPDATE_STATUS_ERROR = "UPDATE_STATUS_ERROR";

export const CANCEL_INVITATION_ACTION = "CANCEL_INVITATION_ACTION";
export const CANCEL_INVITATION_LOADING = "CANCEL_INVITATION_LOADING";
export const CANCEL_INVITATION_SUCCESS = "CANCEL_INVITATION_SUCCESS";
export const CANCEL_INVITATION_ERROR = "CANCEL_INVITATION_ERROR";
