export const UPDATE_STATUS_ACTION = "UPDATE_STATUS_ACTION";
export const UPDATE_STATUS_LOADING = "UPDATE_STATUS_LOADING";
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS";
export const UPDATE_STATUS_ERROR = "UPDATE_STATUS_ERROR";
