export const ATTACH_FAQ_ACTION = "ATTACH_FAQ_ACTION";
export const ATTACH_FAQ_LOADING = "ATTACH_FAQ_LOADING";
export const ATTACH_FAQ_SUCCESS = "ATTACH_FAQ_SUCCESS";
export const ATTACH_FAQ_ERROR = "ATTACH_FAQ_ERROR";
