export const GET_ACTIVITIES_ACTION = "GET_ACTIVITIES_ACTION";
export const GET_ACTIVITIES_LOADING = "GET_ACTIVITIES_LOADING";
export const GET_ACTIVITIES_SUCCESS = "GET_ACTIVITIES_SUCCESS";
export const GET_ACTIVITIES_ERROR = "GET_ACTIVITIES_ERROR";

export const MARK_READ_ACTION = "MARK_READ_ACTION";
export const MARK_READ_LOADING = "MARK_READ_LOADING";
export const MARK_READ_SUCCESS = "MARK_READ_SUCCESS";
export const MARK_READ_ERROR = "MARK_READ_ERROR";
