export const GET_ACTIVITIES_ACTION = "GET_ACTIVITIES_ACTION";
export const GET_ACTIVITIES_LOADING = "GET_ACTIVITIES_LOADING";
export const GET_ACTIVITIES_SUCCESS = "GET_ACTIVITIES_SUCCESS";
export const GET_ACTIVITIES_ERROR = "GET_ACTIVITIES_ERROR";
