export const ATTACH_TEAM_ACTION = "ATTACH_TEAM_ACTION";
export const ATTACH_TEAM_LOADING = "ATTACH_TEAM_LOADING";
export const ATTACH_TEAM_SUCCESS = "ATTACH_TEAM_SUCCESS";
export const ATTACH_TEAM_ERROR = "ATTACH_TEAM_ERROR";
