export const ATTACH_TEAM_ACTION = "ATTACH_TEAM_ACTION";
export const ATTACH_TEAM_LOADING = "ATTACH_TEAM_LOADING";
export const ATTACH_TEAM_SUCCESS = "ATTACH_TEAM_SUCCESS";
export const ATTACH_TEAM_ERROR = "ATTACH_TEAM_ERROR";

export const ACCEPT_TEAM_INVITATION_ACTION = "ACCEPT_TEAM_INVITATION_ACTION";
export const ACCEPT_TEAM_INVITATION_LOADING = "ACCEPT_TEAM_INVITATION_LOADING";
export const ACCEPT_TEAM_INVITATION_SUCCESS = "ACCEPT_TEAM_INVITATION_SUCCESS";
export const ACCEPT_TEAM_INVITATION_ERROR = "ACCEPT_TEAM_INVITATION_ERROR";
