export const GET_ALL_CHALLENGES_ACTION = "GET_ALL_CHALLENGES_ACTION";
export const GET_ALL_CHALLENGES_LOADING = "GET_ALL_CHALLENGES_LOADING";
export const GET_ALL_CHALLENGES_SUCCESS = "GET_ALL_CHALLENGES_SUCCESS";
export const GET_ALL_CHALLENGES_ERROR = "GET_ALL_CHALLENGES_ERROR";

export const DO_SUBSCRIPTION_ACTION = "DO_SUBSCRIPTION_ACTION";
export const DO_SUBSCRIPTION_LOADING = "DO_SUBSCRIPTION_LOADING";
export const DO_SUBSCRIPTION_SUCCESS = "DO_SUBSCRIPTION_SUCCESS";
export const DO_SUBSCRIPTION_ERROR = "DO_SUBSCRIPTION_ERROR";
