export const GET_ALL_CHALLENGES_ACTION = "GET_ALL_CHALLENGES_ACTION";
export const GET_ALL_CHALLENGES_LOADING = "GET_ALL_CHALLENGES_LOADING";
export const GET_ALL_CHALLENGES_SUCCESS = "GET_ALL_CHALLENGES_SUCCESS";
export const GET_ALL_CHALLENGES_ERROR = "GET_ALL_CHALLENGES_ERROR";
