export const CREATE_CHALLENGE_ACTION = "CREATE_CHALLENGE_ACTION";
export const CREATE_CHALLENGE_LOADING = "CREATE_CHALLENGE_LOADING";
export const CREATE_CHALLENGE_SUCCESS = "CREATE_CHALLENGE_SUCCESS";
export const CREATE_CHALLENGE_ERROR = "CREATE_CHALLENGE_ERROR";

export const GET_CHALLENGE_ACTION = "GET_CHALLENGE_ACTION";
export const GET_CHALLENGE_LOADING = "GET_CHALLENGE_LOADING";
export const GET_CHALLENGE_SUCCESS = "GET_CHALLENGE_SUCCESS";
export const GET_CHALLENGE_ERROR = "GET_CHALLENGE_ERROR";

export const UPDATE_CHALLENGE_ACTION = "UPDATE_CHALLENGE_ACTION";
export const UPDATE_CHALLENGE_LOADING = "UPDATE_CHALLENGE_LOADING";
export const UPDATE_CHALLENGE_SUCCESS = "UPDATE_CHALLENGE_SUCCESS";
export const UPDATE_CHALLENGE_ERROR = "UPDATE_CHALLENGE_ERROR";

export const UPDATE_CHALLENGE_VIEWS_ACTION = "UPDATE_CHALLENGE_VIEWS_ACTION";
export const UPDATE_CHALLENGE_VIEWS_LOADING = "UPDATE_CHALLENGE_VIEWS_LOADING";
export const UPDATE_CHALLENGE_VIEWS_SUCCESS = "UPDATE_CHALLENGE_VIEWS_SUCCESS";
export const UPDATE_CHALLENGE_VIEWS_ERROR = "UPDATE_CHALLENGE_VIEWS_ERROR";

export const UPLOAD_FILE_ACTION = "UPLOAD_FILE_ACTION";
export const UPLOAD_FILE_LOADING = "UPLOAD_FILE_LOADING";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_ERROR = "UPLOAD_FILE_ERROR";

export const CHALLENGE_CATEGORIES_ACTION = "CHALLENGE_CATEGORIES_ACTION";
export const CHALLENGE_CATEGORIES_LOADING = "CHALLENGE_CATEGORIES_LOADING";
export const CHALLENGE_CATEGORIES_SUCCESS = "CHALLENGE_CATEGORIES_SUCCESS";
export const CHALLENGE_CATEGORIES_ERROR = "CHALLENGE_CATEGORIES_ERROR";
