export const ATTACH_LEGAL_AGREEMENT_ACTION = "ATTACH_LEGAL_AGREEMENT_ACTION";
export const ATTACH_LEGAL_AGREEMENT_LOADING = "ATTACH_LEGAL_AGREEMENT_LOADING";
export const ATTACH_LEGAL_AGREEMENT_SUCCESS = "ATTACH_LEGAL_AGREEMENT_SUCCESS";
export const ATTACH_LEGAL_AGREEMENT_ERROR = "ATTACH_LEGAL_AGREEMENT_ERROR";
