export const SOLVE_CHALLENGE_ACTION = "SOLVE_CHALLENGE_ACTION";
export const SOLVE_CHALLENGE_LOADING = "SOLVE_CHALLENGE_LOADING";
export const SOLVE_CHALLENGE_SUCCESS = "SOLVE_CHALLENGE_SUCCESS";
export const SOLVE_CHALLENGE_ERROR = "SOLVE_CHALLENGE_ERROR";
