export const SOLVE_CHALLENGE_ACTION = "SOLVE_CHALLENGE_ACTION";
export const SOLVE_CHALLENGE_LOADING = "SOLVE_CHALLENGE_LOADING";
export const SOLVE_CHALLENGE_SUCCESS = "SOLVE_CHALLENGE_SUCCESS";
export const SOLVE_CHALLENGE_ERROR = "SOLVE_CHALLENGE_ERROR";

export const ACCEPT_PARTICIPANT_INVITATION_ACTION =
  "ACCEPT_PARTICIPANT_INVITATION_ACTION";
export const ACCEPT_PARTICIPANT_INVITATION_LOADING =
  "ACCEPT_PARTICIPANT_INVITATION_LOADING";
export const ACCEPT_PARTICIPANT_INVITATION_SUCCESS =
  "ACCEPT_PARTICIPANT_INVITATION_SUCCESS";
export const ACCEPT_PARTICIPANT_INVITATION_ERROR =
  "ACCEPT_PARTICIPANT_INVITATION_ERROR";
