export const FILL_SUBMISSION_FORM_ACTION = "FILL_SUBMISSION_FORM_ACTION";
export const FILL_SUBMISSION_FORM_LOADING = "FILL_SUBMISSION_FORM_LOADING";
export const FILL_SUBMISSION_FORM_SUCCESS = "FILL_SUBMISSION_FORM_SUCCESS";
export const FILL_SUBMISSION_FORM_ERROR = "FILL_SUBMISSION_FORM_ERROR";

export const SUBMISSION_FORM_LIST_ACTION = "SUBMISSION_FORM_LIST_ACTION";
export const SUBMISSION_FORM_LIST_LOADING = "SUBMISSION_FORM_LIST_LOADING";
export const SUBMISSION_FORM_LIST_SUCCESS = "SUBMISSION_FORM_LIST_SUCCESS";
export const SUBMISSION_FORM_LIST_ERROR = "SUBMISSION_FORM_LIST_ERROR";

export const DISQUALIFY_SUBMISSION_FORM_ACTION =
  "DISQUALIFY_SUBMISSION_FORM_ACTION";
export const DISQUALIFY_SUBMISSION_FORM_LOADING =
  "DISQUALIFY_SUBMISSION_FORM_LOADING";
export const DISQUALIFY_SUBMISSION_FORM_SUCCESS =
  "DISQUALIFY_SUBMISSION_FORM_SUCCESS";
export const DISQUALIFY_SUBMISSION_FORM_ERROR =
  "DISQUALIFY_SUBMISSION_FORM_ERROR";

export const JUDGE_SUBMISSION_FORM_ACTION = "JUDGE_SUBMISSION_FORM_ACTION";
export const JUDGE_SUBMISSION_FORM_LOADING = "JUDGE_SUBMISSION_FORM_LOADING";
export const JUDGE_SUBMISSION_FORM_SUCCESS = "JUDGE_SUBMISSION_FORM_SUCCESS";
export const JUDGE_SUBMISSION_FORM_ERROR = "JUDGE_SUBMISSION_FORM_ERROR";
