export const ATTACH_RESOURCES_ACTION = "ATTACH_RESOURCES_ACTION";
export const ATTACH_RESOURCES_LOADING = "ATTACH_RESOURCES_LOADING";
export const ATTACH_RESOURCES_SUCCESS = "ATTACH_RESOURCES_SUCCESS";
export const ATTACH_RESOURCES_ERROR = "ATTACH_RESOURCES_ERROR";
