export const UPDATE_BUSINESS_TAGS_ACTION = "UPDATE_BUSINESS_TAGS_ACTION";
export const UPDATE_BUSINESS_TAGS_LOADING = "UPDATE_BUSINESS_TAGS_LOADING";
export const UPDATE_BUSINESS_TAGS_SUCCESS = "UPDATE_BUSINESS_TAGS_SUCCESS";
export const UPDATE_BUSINESS_TAGS_ERROR = "UPDATE_BUSINESS_TAGS_ERROR";

export const PRESERVE_BUSSINESS_TAG_ACTION = "PRESERVE_BUSSINESS_TAG_ACTION";
export const PRESERVE_BUSSINESS_TAG_SUCCESS = "PRESERVE_BUSSINESS_TAG_SUCCESS";

export const INDUSTRIES_OPTIONS_ACTION = "INDUSTRIES_OPTIONS_ACTION";
export const INDUSTRIES_OPTIONS_LOADING = "INDUSTRIES_OPTIONS_LOADING";
export const INDUSTRIES_OPTIONS_SUCCESS = "INDUSTRIES_OPTIONS_SUCCESS";
export const INDUSTRIES_OPTIONS_ERROR = "INDUSTRIES_OPTIONS_ERROR";

export const SERVICES_OPTIONS_ACTION = "SERVICES_OPTIONS_ACTION";
export const SERVICES_OPTIONS_LOADING = "SERVICES_OPTIONS_LOADING";
export const SERVICES_OPTIONS_SUCCESS = "SERVICES_OPTIONS_SUCCESS";
export const SERVICES_OPTIONS_ERROR = "SERVICES_OPTIONS_ERROR";

export const TECHNOLOGIES_OPTIONS_ACTION = "TECHNOLOGIES_OPTIONS_ACTION";
export const TECHNOLOGIES_OPTIONS_LOADING = "TECHNOLOGIES_OPTIONS_LOADING";
export const TECHNOLOGIES_OPTIONS_SUCCESS = "TECHNOLOGIES_OPTIONS_SUCCESS";
export const TECHNOLOGIES_OPTIONS_ERROR = "TECHNOLOGIES_OPTIONS_ERROR";

export const BUSINESS_MODELS_OPTIONS_ACTION = "BUSINESS_MODELS_OPTIONS_ACTION";
export const BUSINESS_MODELS_OPTIONS_LOADING =
  "BUSINESS_MODELS_OPTIONS_LOADING";
export const BUSINESS_MODELS_OPTIONS_SUCCESS =
  "BUSINESS_MODELS_OPTIONS_SUCCESS";
export const BUSINESS_MODELS_OPTIONS_ERROR = "BUSINESS_MODELS_OPTIONS_ERROR";

export const TARGET_MARKET_OPTIONS_ACTION = "TARGET_MARKET_OPTIONS_ACTION";
export const TARGET_MARKET_OPTIONS_LOADING = "TARGET_MARKET_OPTIONS_LOADING";
export const TARGET_MARKET_OPTIONS_SUCCESS = "TARGET_MARKET_OPTIONS_SUCCESS";
export const TARGET_MARKET_OPTIONS_ERROR = "TARGET_MARKET_OPTIONS_ERROR";

export const GEOGRAPHICAL_MARKET_OPTIONS_ACTION =
  "GEOGRAPHICAL_MARKET_OPTIONS_ACTION";
export const GEOGRAPHICAL_MARKET_OPTIONS_LOADING =
  "GEOGRAPHICAL_MARKET_OPTIONS_LOADING";
export const GEOGRAPHICAL_MARKET_OPTIONS_SUCCESS =
  "GEOGRAPHICAL_MARKET_OPTIONS_SUCCESS";
export const GEOGRAPHICAL_MARKET_OPTIONS_ERROR =
  "GEOGRAPHICAL_MARKET_OPTIONS_ERROR";
