export const UPDATE_DESC_ACTION = "UPDATE_DESC_ACTION";
export const UPDATE_DESC_LOADING = "UPDATE_DESC_LOADING";
export const UPDATE_DESC_SUCCESS = "UPDATE_DESC_SUCCESS";
export const UPDATE_DESC_ERROR = "UPDATE_DESC_ERROR";
