export const UPDATE_DESC_ACTION = "UPDATE_DESC_ACTION";
export const UPDATE_DESC_LOADING = "UPDATE_DESC_LOADING";
export const UPDATE_DESC_SUCCESS = "UPDATE_DESC_SUCCESS";
export const UPDATE_DESC_ERROR = "UPDATE_DESC_ERROR";

export const GET_TAGS_ACTION = "GET_TAGS_ACTION";
export const GET_TAGS_LOADING = "GET_TAGS_LOADING";
export const GET_TAGS_SUCCESS = "GET_TAGS_SUCCESS";
export const GET_TAGS_ERROR = "GET_TAGS_ERROR";
