export const ATTACH_SUBMISSION_FORM_ACTION = "ATTACH_SUBMISSION_FORM_ACTION";
export const ATTACH_SUBMISSION_FORM_LOADING = "ATTACH_SUBMISSION_FORM_LOADING";
export const ATTACH_SUBMISSION_FORM_SUCCESS = "ATTACH_SUBMISSION_FORM_SUCCESS";
export const ATTACH_SUBMISSION_FORM_ERROR = "ATTACH_SUBMISSION_FORM_ERROR";
