export const ATTACH_JUDGES_NDA_ACTION = "ATTACH_JUDGES_NDA_ACTION";
export const ATTACH_JUDGES_NDA_LOADING = "ATTACH_JUDGES_NDA_LOADING";
export const ATTACH_JUDGES_NDA_SUCCESS = "ATTACH_JUDGES_NDA_SUCCESS";
export const ATTACH_JUDGES_NDA_ERROR = "ATTACH_JUDGES_NDA_ERROR";
