export const ATTACH_OVERVIEW_ACTION = "ATTACH_OVERVIEW_ACTION";
export const ATTACH_OVERVIEW_LOADING = "ATTACH_OVERVIEW_LOADING";
export const ATTACH_OVERVIEW_SUCCESS = "ATTACH_OVERVIEW_SUCCESS";
export const ATTACH_OVERVIEW_ERROR = "ATTACH_OVERVIEW_ERROR";
