export const ATTACH_JUDGES_ACTION = "ATTACH_JUDGES_ACTION";
export const ATTACH_JUDGES_LOADING = "ATTACH_JUDGES_LOADING";
export const ATTACH_JUDGES_SUCCESS = "ATTACH_JUDGES_SUCCESS";
export const ATTACH_JUDGES_ERROR = "ATTACH_JUDGES_ERROR";
