export const EMAIL_VERIFICATION_ACTION = "EMAIL_VERIFICATION_ACTION";
export const EMAIL_VERIFICATION_LOADING = "EMAIL_VERIFICATION_LOADING";
export const EMAIL_VERIFICATION_SUCCESS = "EMAIL_VERIFICATION_SUCCESS";
export const EMAIL_VERIFICATION_ERROR = "EMAIL_VERIFICATION_ERROR";

export const RESEND_EMAIL_VERIFICATION_ACTION =
  "RESEND_EMAIL_VERIFICATION_ACTION";
export const RESEND_EMAIL_VERIFICATION_LOADING =
  "RESEND_EMAIL_VERIFICATION_LOADING";
export const RESEND_EMAIL_VERIFICATION_SUCCESS =
  "RESEND_EMAIL_VERIFICATION_SUCCESS";
export const RESEND_EMAIL_VERIFICATION_ERROR =
  "RESEND_EMAIL_VERIFICATION_ERROR";
