export const GET_MY_CHALLENGES_ACTION = "GET_MY_CHALLENGES_ACTION";
export const GET_MY_CHALLENGES_LOADING = "GET_MY_CHALLENGES_LOADING";
export const GET_MY_CHALLENGES_SUCCESS = "GET_MY_CHALLENGES_SUCCESS";
export const GET_MY_CHALLENGES_ERROR = "GET_MY_CHALLENGES_ERROR";
