export const SHARE_LINK_ACTION = "SHARE_LINK_ACTION";
export const SHARE_LINK_LOADING = "SHARE_LINK_LOADING";
export const SHARE_LINK_SUCCESS = "SHARE_LINK_SUCCESS";
export const SHARE_LINK_ERROR = "SHARE_LINK_ERROR";
